#!/bin/sh

env=""
version=""

printf "Please provide environment: "
read env

printf "Please provide version: "
read version

echo "#######################################"
echo ""
echo "######    ######    ######    ######"
echo "#         #         #         #    #"
echo "#         ######    ######    ######"
echo "#              #         #    #"
echo "######    ######    ######    #"
echo ""
echo "#######################################"



if [ "$env" = "TEST" ] ;
then
    npm run testbuild
elif [ "$env" = "UAT" ] ;
then
    npm run uatbuild
elif [ "$env" = "PREPROD" ] ;
then
    npm run ppbuild
elif [ "$env" = "PROD" ] ;
then
    npm run prodbuild
else
    echo "Error: Please provide valid environment, [PROD, TEST, UAT]";
    exit
fi

DATE=$(date +"%d-%m-%Y")
TIME=$(date +"%H:%M")

if [ -z "$env" ]
then
    $env = ""
    echo "##################################"
    echo "Environment was not provided."
    echo "##################################"
fi

if [ -z "$version" ]
then
    $version = ""
    echo "##################################"
    echo "Version Number was not provided."
    echo "##################################"
fi

cd sdssp && tar -czvf ../sdssp-$DATE-$TIME-$version-$env.tar.gz * && cd ..

sudo rm -rf sdssp

echo $DATE
echo $TIME
