services:
  - type: web
    name: formyfinite
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DATA_ENCRYPTION_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
