import {z} from 'zod';
export const fail=(status,message,details)=>Object.assign(new Error(message),{status,details});
export const email=z.email().max(254).transform(v=>v.toLowerCase());
export const password=z.string().min(10).max(128);
export const field=z.object({id:z.string().regex(/^[a-zA-Z0-9_-]{1,64}$/).refine(x=>!Object.getOwnPropertyNames(Object.prototype).includes(x)),kind:z.enum(['text','textarea','email','number','date','radio','checkbox','select','file','password','info','link']),label:z.string().trim().min(1).max(200),hint:z.string().max(1000).default(''),required:z.boolean().default(false),choices:z.array(z.string().trim().min(1).max(150)).max(80).default([]),min:z.number().finite().nullable().optional(),max:z.number().finite().nullable().optional(),when:z.object({field:z.string(),operator:z.enum(['equals','differs','contains','answered']),value:z.string().max(1000)}).nullable().optional()});
export const definition=z.object({title:z.string().trim().min(1).max(160),description:z.string().max(2000).default(''),accent:z.string().regex(/^#[a-fA-F0-9]{6}$/).default('#6850d8'),confirmation:z.string().min(1).max(1000).default('Thank you! Your response has been saved.'),fields:z.array(field).max(100)}).superRefine((v,ctx)=>{const seen=new Set();v.fields.forEach((f,i)=>{const err=message=>ctx.addIssue({code:'custom',message,path:['fields',i]});if(seen.has(f.id))err('Duplicate question identifier');if(f.when&&!seen.has(f.when.field))err('Conditions must reference an earlier question');if(['radio','checkbox','select'].includes(f.kind)&&(!f.choices.length||new Set(f.choices).size!==f.choices.length))err('Provide unique, nonempty choices');if(f.min!=null&&f.max!=null&&f.min>f.max)err('Minimum exceeds maximum');if(f.kind!=='number'&&((f.min??0)<0||(f.max??0)<0))err('Lengths cannot be negative');seen.add(f.id)})});
export function isVisible(f,answers,shown){if(!f.when)return true;const c=f.when;if(!shown.has(c.field))return false;const v=answers[c.field],s=Array.isArray(v)?v.map(String):String(v??'');if(c.operator==='answered')return s.length>0;if(c.operator==='contains')return s.includes(c.value);const eq=Array.isArray(s)?s.includes(c.value):s===c.value;return c.operator==='equals'?eq:!eq;}
export function answersFor(fields,raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw fail(400,'Invalid answers');const answers={},errors={},shown=new Set();for(const f of fields){if(!isVisible(f,raw,shown))continue;shown.add(f.id);if(['info','link'].includes(f.kind))continue;const v=raw[f.id];if(v==null||v===''||Array.isArray(v)&&v.length===0){if(f.required)errors[f.id]='An answer is required';continue;}if(f.kind==='number'){if(typeof v!=='number'||!Number.isFinite(v)||(f.min!=null&&v<f.min)||(f.max!=null&&v>f.max))errors[f.id]='Enter a number within the allowed range';else answers[f.id]=v;continue;}if(f.kind==='checkbox'){if(!Array.isArray(v)||v.some(x=>!f.choices.includes(x))||new Set(v).size!==v.length)errors[f.id]='Choose valid options';else answers[f.id]=v;continue;}if(f.kind==='file'){if(typeof v!=='object'||typeof v.name!=='string'||typeof v.data!=='string'||!/^data:(text\/plain|application\/pdf|image\/(png|jpeg));base64,[A-Za-z0-9+/]*={0,2}$/.test(v.data)||v.data.length>1400000||Buffer.from(v.data.split(',')[1]||'','base64').length>1048576)errors[f.id]='Upload PDF, PNG, JPEG or TXT up to 1 MB';else answers[f.id]={name:v.name.slice(0,150),data:v.data};continue;}if(typeof v!=='string'||v.length>10000){errors[f.id]='Enter text up to 10,000 characters';continue;}if(f.min!=null&&v.length<f.min||f.max!=null&&v.length>f.max)errors[f.id]='Check the answer length';if(f.kind==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))errors[f.id]='Enter a valid email address';if(f.kind==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v))errors[f.id]='Enter a valid date';if(['radio','select'].includes(f.kind)&&!f.choices.includes(v))errors[f.id]='Select one of the choices';answers[f.id]=v;}if(Object.keys(errors).length)throw fail(400,'Please check your answers',errors);return answers;}
export function csv(v){let s=typeof v==='object'?JSON.stringify(v):String(v??'');if(/^\s*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
